project: "testing"
jobs:
- name: "Hello world!"
  description: "Job from scheduler Quickstart"
  frequency: "* * * * *"
  timezone: "America/Los_Angeles"
  target:
    destination: "Pub/Sub"
    topic: "cron-job"
  payload: "hello cron!"
